// Action types
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_OPEN_NOTIFICATION = 'SET_OPEN_NOTIFICATION';
export const SET_NOTIFICATION_SEVERITY = 'SET_NOTIFICATION_SEVERITY';
export const SET_OPEN_DIALOG = 'SET_OPEN_NOTIFICATION';
export const SET_DIALOG_MESSAGE = 'SET_OPEN_NOTIFICATION';

